name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: '.node-version'
          cache: 'yarn'                            # Yarn v1 用の組み込みキャッシュ
          cache-dependency-path: |
            yarn.lock

      - run: yarn install --frozen-lockfile        # v1 は --frozen-lockfile
      - run: yarn test
