name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'yarn'                            # Yarn v1 用の組み込みキャッシュ
          cache-dependency-path: |
            yarn.lock

      - run: yarn install --frozen-lockfile        # v1 は --frozen-lockfile
      - run: yarn test
